import Image from "next/image";
import BlogFeed from "@/components/BlogFeed";
import SharePortfolio from "@/components/SharePortfolio";
import SiteHeader from "@/components/SiteHeader";
import { data } from "@/lib/content";

export default function Home() {
  return <>
    <a className="skip-link" href="#main">Skip to main content</a><SiteHeader />
    <main id="main">
      <section className="hero section-shell" id="home" aria-labelledby="hero-title">
        <div className="hero-copy"><p className="eyebrow">Aditya Shah · Bhopal, India</p><h1 id="hero-title">Technical leadership.<br /><span>Production depth.</span></h1><p className="hero-lede">I lead technical teams, solve production problems, and build useful automation.</p><p className="hero-summary">I lead Hosting Support at WPMU DEV while staying hands-on with infrastructure, incidents, security, and customer escalations. I also build and write about practical AI workflows.</p><div className="hero-actions"><a className="button button-primary" href="#impact">Explore my work</a><a className="text-link" href="/recruiter/">Recruiter overview</a><SharePortfolio /></div></div>
        <figure className="hero-profile"><div className="portrait-wrap"><Image src="/images/aditya-shah.jpg" alt="Aditya Shah" width={460} height={460} priority /></div><figcaption><strong>Aditya Shah</strong><span>Hosting Support Manager & DevOps Engineer</span><p>Technical leadership · Cloud infrastructure · Applied AI</p></figcaption></figure>
        <div className="hero-foot"><p>Based in Bhopal, India · Working with distributed teams</p><a href="#community">Community builder since 2015</a></div>
      </section>
      <section className="proof-strip" aria-label="Career proof points"><div className="section-shell proof-grid">{data.stats.map((stat) => <article key={stat.label}><strong>{stat.value.toLocaleString("en-IN")}{stat.suffix}</strong><h2>{stat.label}</h2><p>{stat.detail}</p></article>)}</div></section>
      <section className="section impact-section" id="impact"><div className="section-shell"><header className="section-intro split-intro"><div><p className="eyebrow">Selected work</p><h2>Tools and ideas<br />from the work.</h2></div><p>Public examples of how I investigate production issues, apply AI, and make operational work repeatable.</p></header><div className="impact-grid">{data.tools.map((tool) => <article className="impact-card" key={tool.name}><p className="eyebrow">{tool.category}</p><h3>{tool.name}</h3><p className="project-description">{tool.description}</p><dl className="project-details"><div><dt>The problem</dt><dd>{tool.challenge}</dd></div><div><dt>My approach</dt><dd>{tool.approach}</dd></div></dl><ul className="tag-list">{tool.tags.map((tag) => <li key={tag}>{tag}</li>)}</ul><a className="text-link project-link" href={tool.url} target="_blank" rel="noopener noreferrer">{tool.label}</a></article>)}</div></div></section>
      <section className="section section-shell" id="capabilities"><header className="section-intro split-intro"><div><p className="eyebrow">Where I operate</p><h2>People. Systems.<br />Better decisions.</h2></div><p>My work starts where a customer problem meets a production system, then continues into the team, process, or tool that helps prevent it happening again.</p></header><div className="capability-list">{data.whatIDo.map((item, index) => <article key={item.title} className="capability-row"><p className="row-index">0{index + 1}</p><div><h3>{item.title}</h3><p>{item.description}</p></div><ul className="tag-list">{item.tags.map((tag) => <li key={tag}>{tag}</li>)}</ul></article>)}</div></section>
      <section className="section experience-section" id="experience"><div className="section-shell"><header className="section-intro split-intro"><div><p className="eyebrow">Experience</p><h2>Leadership without<br />leaving the terminal.</h2></div><p>Team leadership, technical customer experience, and hands-on production operations. My WPMU DEV tenure began in February 2019; the role below reflects my current responsibilities.</p></header><div className="experience-list">{data.experience.map((experience, index) => <article key={`${experience.company}-${experience.period}`} className="experience-row"><div className="experience-meta"><p>0{index + 1}</p><span>{experience.period}</span></div><div className="experience-title"><h3>{experience.role}</h3><p>{experience.company} · {experience.remote ? "Remote" : experience.type}</p></div><ul>{experience.highlights.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></div></section>
      <section className="section community-section" id="community"><div className="section-shell community-layout"><header className="section-intro"><p className="eyebrow">Community & open source</p><h2>It started with<br />a meetup at home.</h2><p>On 2 October 2015, I hosted the first WordPress Bhopal meetup at my home. The second was at a café, which I funded myself. We started small, with people who wanted to learn together.</p><p>That same idea still guides me: make it easier for students and developers in a city like Bhopal to find their people, build something, and take the next step.</p><a className="text-link" href="https://profiles.wordpress.org/ethicaladitya/" target="_blank" rel="me noopener noreferrer">WordPress.org profile</a></header><div className="community-grid">{data.community.map((item) => <article key={item.event}><p className="eyebrow">{item.years}</p><h3>{item.event}</h3><strong>{item.role}</strong><p>{item.description}</p></article>)}<article className="community-open-source"><p className="eyebrow">Speaking & contribution</p><h3>Sharing what I learn.</h3><p>Talks at WordCamp Asia, Nepal, Mumbai, and Kochi on performance, hosting infrastructure, and WP-CLI. Contributions to WP-CLI and the wider WordPress ecosystem.</p></article></div></div></section>
      <BlogFeed fallback={data.blog} />
      <section className="contact-section" id="contact"><div className="section-shell contact-layout"><p className="eyebrow">Let’s talk</p><h2>Good conversations<br />start with a real problem.</h2><p>Talk to me about technical leadership, customer engineering, cloud infrastructure, practical AI, or developer communities.</p><div className="contact-actions"><a className="button button-primary" href={`mailto:${data.meta.email}`}>Email Aditya</a><a className="text-link" href={data.meta.linkedin} target="_blank" rel="me noopener noreferrer">Connect on LinkedIn</a></div></div></section>
    </main><footer className="site-footer"><div className="section-shell"><a className="footer-mark" href="#home">AS<span>.</span></a><p>Technical leadership · Cloud infrastructure · Applied AI</p><nav aria-label="Social links"><a href={data.meta.github} rel="me">GitHub</a><a href={data.meta.linkedin} rel="me">LinkedIn</a><a href="https://adityashah.blog/" rel="me">Blog</a></nav><p>© {new Date().getFullYear()} Aditya Shah</p></div></footer>
  </>;
}
