"use client";

import { useEffect, useState } from "react";
type Post = { title: string; slug: string; category: string; excerpt: string; date: string };
type WPPost = { title?: { rendered?: string }; excerpt?: { rendered?: string }; link?: string; date?: string; _embedded?: { "wp:term"?: Array<Array<{ name?: string }>> } };
const decode = (value = "") => value.replace(/<[^>]*>/g, " ").replace(/&hellip;/g, "…").replace(/&#8217;/g, "’").replace(/&#8211;/g, "–").replace(/&amp;/g, "&").replace(/\s+/g, " ").trim();
export default function BlogFeed({ fallback }: { fallback: Post[] }) {
  const [posts, setPosts] = useState(fallback);
  useEffect(() => { const controller = new AbortController(); fetch("https://adityashah.blog/wp-json/wp/v2/posts?per_page=3&_embed=wp:term", { signal: controller.signal }).then((response) => { if (!response.ok) throw new Error("Blog unavailable"); return response.json(); }).then((items: WPPost[]) => setPosts(items.map((post) => ({ title: decode(post.title?.rendered), excerpt: decode(post.excerpt?.rendered), slug: post.link || "https://adityashah.blog/", date: post.date || "", category: post._embedded?.["wp:term"]?.[0]?.[0]?.name || "Article" })))).catch((error) => { if (error.name !== "AbortError") console.info("Using the built-in article list."); }); return () => controller.abort(); }, []);
  return <section className="section writing-section" id="writing"><div className="section-shell"><header className="section-intro split-intro"><div><p className="eyebrow">Field notes</p><h2>Writing from the work.</h2></div><p>I document the decisions behind production debugging, WordPress architecture, automation, and AI-assisted operations.</p></header><div className="article-list">{posts.map((post, index) => <article key={post.slug}><p className="article-number">0{index + 1}</p><div><p className="eyebrow">{post.category} · {post.date ? new Date(post.date).toLocaleDateString("en-GB", { month: "short", year: "numeric" }) : "Latest"}</p><h3><a href={post.slug} target="_blank" rel="noopener noreferrer">{post.title}</a></h3><p>{post.excerpt}</p></div><a aria-label={`Read ${post.title}`} className="article-arrow" href={post.slug} target="_blank" rel="noopener noreferrer">↗</a></article>)}</div><a className="text-link writing-all" href="https://adityashah.blog/articles/" target="_blank" rel="me noopener noreferrer">Read all articles <span aria-hidden="true">→</span></a></div></section>;
}
